### ISSUE TITLE
Layout — Swag sur la navbar

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#17]

**Comment by tchret** [comment]
@Papillard : first draft
![image](https://cloud.githubusercontent.com/assets/4539476/9873161/33179292-5b9e-11e5-8c15-79ba45f78172.png)

**Comment by tchret** [comment]
là c'est centré
![image](https://cloud.githubusercontent.com/assets/4539476/9873653/83d96914-5ba1-11e5-86af-29c4576b3d1a.png)

**Comment by Papillard** [comment]
Mes remarques 

- a quoi sert le menu déroulant ? il faut pas que ce soit gadget :)
- le bouton postuler doit "répondre" aux trois points de gauche graphiquement
- sur les pages en anglais on a pas ondemand donc ca va faire bizarre deux liens à gauche du wagon et un à droite..
