### ISSUE TITLE
Home — section features

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#22]

**Comment by Papillard** [comment]
Virer les 3 points "Preparation/Bootcamp/Nouveau moi"
Remplacer par 6 features façon Slack avec des icones. Les features en question :

Hard skills
- Web-development (ruby, HTML/CSS/JS, Postgres, SQL, etc..)
- Software engineering & algorithmic => code

Soft skills
- Advanced workflow (user-stories, pull-request on Github)
- Startup tools (Heroku, Stripe, Mandrill, AWS) 

After
- Land a job (citer 3 gus)
- Build product (kudoz => 1.2M, Medpics => 400k, etc..)

**Comment by tchret** [comment]
![image](https://cloud.githubusercontent.com/assets/4539476/9880747/3d6cebb4-5bcd-11e5-8429-bf5cff0c30ee.png)
