### ISSUE TITLE
Program — add learning curve + figures (1 bootcamp, 9 weeks, 25 students)

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#23]

**Comment by flexbox** [comment]
@Papillard Maybe you could use this https://gionkunz.github.io/chartist-js/

**Comment by Papillard** [comment]
bonne idée :) mais @tchret a déjà mockupé un truc de fou custom. C'est pas vt une courbe avec de la vraie data, mais plutot une illlustratrion des différents modules du programme et de la progression des élèves.

**Comment by Papillard** [comment]
@tchret peut etre un poil long mais pour le lancement dans les villes j'avais écrit le détail de chaque module => https://hackpad.com/Wording-program-page-dFX8hMQAHvq

tu peux reprendre ça pour le wording des différents modules
