### ISSUE TITLE
Oval avatar pictures only visible on iOS

### ISSUE THREAD

**Issue by ManyBaby** [lewagon/www#256]
@Papillard go on [this page](https://www.lewagon.com/employers) with your phone or someone else's iPhone.
In case you cannot reproduce it I made a screenshot :
![slack for ios upload](https://cloud.githubusercontent.com/assets/7141798/16173465/854b78e2-35a2-11e6-828e-fca9e2ed01f4.jpg)

Hope this helps

**Comment by krokrob** [comment]
@ssaunier @Papillard, impossible de reproduire ce bug sur iphone 4S ou 6S dès que je trouve un iphone 5 je teste

**Comment by ssaunier** [comment]
@krokrob ça a du être fixé entre temps. No Repro sur mon 5C.
