### ISSUE TITLE
Group cities under country / continent for the navbar

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#262]
For the moment it's hard-coded in the view, cf https://github.com/lewagon/www/pull/261

<img width="1267" alt="screen shot 2016-07-03 at 12 52 02" src="https://cloud.githubusercontent.com/assets/2471555/16546312/fc23ce4e-411c-11e6-968b-2cfc5162b1a1.png">

**Comment by ssaunier** [comment]
The alumni API needs to return the list of cities as a structured JSON:

```json
[
  {
    "group": "France",
    "icon": "inline some SVG, move that out of the `www`",
    "cities": [
      // put cities in here, ordered
    ]
  }
]
```
