### ISSUE TITLE
Company pictures are not showing up on Lisbon page

### ISSUE THREAD

**Issue by ssaunier** [lewagon/www#269]
Suspecting an unclosed tag in the "marketing specifics" of the city because it works fine on other `/:city` pages:

👉  https://www.lewagon.com/lisbon

![screen shot 2016-09-04 at 12 40 34](https://cloud.githubusercontent.com/assets/414418/18230483/f022f960-729c-11e6-8ed1-e9429cf3e126.png)

**Comment by Eschults** [comment]
Indeed, added a closing `</div>` tag at the end, is there a trick to refresh cache though @ssaunier ? The display isn't fixed yet despite the change I made in lisbon's `:marketing_specifics`.

**Comment by Eschults** [comment]
looks fixed to me :)

![capture d ecran 2016-09-05 a 15 01 38](https://cloud.githubusercontent.com/assets/8090140/18248622/b1f474ce-7379-11e6-9e2e-7e15e10cc6f0.png)

**Comment by ssaunier** [comment]
👌 🎉
