### ISSUE TITLE
/tv

### ISSUE THREAD

**Issue by ssaunier** [lewagon/www#276]
- DemoDay -> new demo day page
- Workshops -> using OnDemand tracks
- Aperotalks -> that could be a new page on `www`.

**Comment by cedricmenteau** [comment]
@ssaunier Currently working on it. The most recent videos will show up on /blog. 

Thinking about 2 partials we could add on `/city-name`:
- slider with links to `/demoday/xx`from the current city
- slider with the 3 most recent Le Wagon talks from the current city (for cities having their own playlist on YT)
