### ISSUE TITLE
Lesson about ActiveRecord timestamps null: false is outdated

### ISSUE THREAD

**Issue by jooleeanh** [lewagon/www#292]
As mentioned in this article, [Adding null: false isn't necessary anymore because it is the default.](https://teamtreehouse.com/community/why-does-ttimestamps-not-include-null-false-in-video-230)

Here is one page of your lectures where it's written:
https://karr.lewagon.org/lectures/db/03-active-record/#/3/3

**Comment by ssaunier** [comment]
Thanks! Fixed :chec
