### ISSUE TITLE
Tabbing in the application form

### ISSUE THREAD

**Issue by PhilippvH1** [lewagon/www#345]
When I go to https://www.lewagon.com/apply/berlin and fill in my profile, I always have to use `Tab` twice to get to the next field. Would be awesome if it were only once.

**Comment by ssaunier** [comment]
Hmm, juste tested it on Firefox and Chrome on my Mac and I don't. Can you specify which browser you're using? Make a gif with [Recordit](http://recordit.co/) and upload it?

**Comment by alex-felix** [comment]
this happens for the inputs referer/linkedin/codeacademy only

**Comment by ssaunier** [comment]
Fixed with https://github.com/lewagon/www/commit/048dd2c83784211e97ffdaa7ecb72d85e39ff7fa

**Comment by alex-felix** [comment]
thanks 👍
