### ISSUE TITLE
Add a caret to the apply region dropdown

### ISSUE THREAD

**Issue by alex-felix** [lewagon/www#346]
The region dropdown (Europe/France/World) doesnt look like a dropdown and would benefit from adding a caret to the right of the region

<img width="349" alt="screen shot 2017-04-04 at 12 57 30" src="https://cloud.githubusercontent.com/assets/16181471/24655517/767f63aa-1936-11e7-9144-018d40692cb1.png">

**Comment by ssaunier** [comment]
Actually, not that easy because of the `prerender` feature which chokes on the ReactBootstrap component that we use :(

**Comment by ssaunier** [comment]
Caret added
