### ISSUE TITLE
Typical day banner bug on hover of items

### ISSUE THREAD

**Issue by alex-felix** [lewagon/www#347]
https://www.lewagon.com/program -> Typical Day
Hover over different parts of the day
The content shift up when you change selection
The problem is due to the text at `16h30` becoming two lines somehow...

![day](https://cloud.githubusercontent.com/assets/16181471/24837148/2897090c-1d25-11e7-86d0-8d036194fdab.gif)

**Comment by alex-felix** [comment]
@cedricmenteau this got removed right?

**Comment by cedricmenteau** [comment]
@alex-felix Not done yet but will do 👌
