### ISSUE TITLE
VAE page

### ISSUE THREAD

**Issue by krokrob** [lewagon/www#377]
We need a Validation of Acquired Experience page for certification process. Here is the wording:

## 1- Les conditions de recevabilité de la demande des candidats 

Les conditions de recevabilité sont les suivantes : « Toute personne, quels que soient son âge, sa nationalité, son statut et son niveau de formation, qui justifie d'au moins 1 an d'expérience en rapport direct avec la certification visée, peut prétendre à la VAE. Cette certification qui peut être un diplôme, un titre ou un certificat de qualification professionnelle doit être inscrite au Répertoire national des certifications professionnelles (RNCP) ». ( http://www.vae.gouv.fr/)

## 2- Exemples de preuves sur lesquelles se base le jury, au regard des compétences décrites

- Fiches de paie
- Porte-folio
- Lettres de recommandation d'employeurs ou de clients
- Curriculum Vitae
- Revue du code source (GITHUB = Facebook des développeurs = ils partagent leurs dossiers de code)
- ou tout autre élément que le candidat jugera pertinent

## 3- En cas de validation partielle

Les compétences composant la certification par la V.A.E. sont les mêmes que celles acquises par la formation.

Préconisations que donnera le jury pour l'obtention de la certification dans sa totalité: une expérience complémentaire ou le suivi d'une formation en lien avec les compétences manquantes.

La durée de la validation partielle est permanente.

## 4- Description de la procédure de VAE:

<img width="640" alt="capture d ecran 2017-05-16 a 11 57 38" src="https://cloud.githubusercontent.com/assets/9978111/26101137/666e2f80-3a30-11e7-8170-681540bbc14a.png">

Ping @monsieurpaillard for further explanations

**Comment by monsieurpaillard** [comment]
@krokrob @ssaunier c'est parfait pour moi.
