### ISSUE TITLE
Demoday page not displaying the right pitch infos.

### ISSUE THREAD

**Issue by edouardfoussier** [lewagon/www#400]
Example: On the Demoday page.
When clicking on timzy, I get to the right part of the video, but the url (https://www.lewagon.com/demoday/48/timzy) changes to the SOSFood one (so does the project info displayed on the side and the highlight of the sosfood button.

Same story when clicking on 6 button projects out of 10.

**Comment by edouardfoussier** [comment]
<img width="1117" alt="screenshot 2017-06-02 12 05 13" src="https://cloud.githubusercontent.com/assets/3153088/26721825/b1156aac-478d-11e7-8f46-1b452d72960b.png">

**Comment by cedricmenteau** [comment]
Fixed by reordering projects.
