### ISSUE TITLE
page thanks

### ISSUE THREAD

**Issue by tchret** [lewagon/www#42]
TODO list pour le mano qui a candidaté :

```
- [x] J'ai postulé
- [ ] Abonnement Twitter de la ville
- [ ] Abonnement Groupe Meetup de la ville
- [ ] Officiel: commence CodeCademy Ruby English
```

**Comment by tchret** [comment]
@ssaunier Est-ce qu'on demande au mec de nous filer son codecademy à ce moment là pour lancer le bot qui détecte l'avancement ?

**Comment by ssaunier** [comment]
Yes on peut :+1:
