### ISSUE TITLE
Some infos on Belo Horizonte (Brazil) Batch are wrong

### ISSUE THREAD

**Issue by andrealmar** [lewagon/www#527]
Hi, On the page regarding Belo Horizonte batch of LeWagon (https://www.lewagon.com/belo-horizonte) there are some info I believe it's wrong. 

For example: The location (RAJA VALLEY) it's with the wrong address. The **correct** address is: _Av. Raja Gabaglia, 4343 - Belo Horizonte/MG_ **instead of** Av. Afonso Pena, 2881, Belo Horizonte

Also on the same page it's saying that: In Belo Horizonte, lectures are given in English

But the lectures will be given in Portuguese. 

Thanks,

**Comment by ssaunier** [comment]
Thank you, I'm updating the page right now!

**Comment by andrealmar** [comment]
No worries. Also need to correct the map which is pointing to the old address
