### ISSUE TITLE
Kitt - Resources - YouTube link

### ISSUE THREAD

**Issue by andrealmar** [lewagon/www#543]
I don't know if here is the right place to open this issue but anyways...on Kitt when you add a resource from YouTube (e.g a talk like this one: https://www.youtube.com/watch?v=BZbW8FAvf00) it doesn't display the right link to the resource. 

An actual example could be seen on Kitt if you go to Resources --> Newest --> Page 2 and click on the link below:

<img width="760" alt="screen shot 2017-12-02 at 21 17 23" src="https://user-images.githubusercontent.com/537826/33520645-43da7b72-d7a6-11e7-8418-9b3810fb754b.png">

It will redirect you to the main YouTube page instead of the proper talk. 

When you try to add a new resource which is a YouTube link the same happens:

<img width="622" alt="screen shot 2017-12-02 at 21 18 42" src="https://user-images.githubusercontent.com/537826/33520658-6fd8eae2-d7a6-11e7-8513-d30fe6387667.png">

<img width="651" alt="screen shot 2017-12-02 at 21 19 14" src="https://user-images.githubusercontent.com/537826/33520664-88ded4f2-d7a6-11e7-9a23-a86d2d5b2012.png">

**Comment by ssaunier** [comment]
Hi @andrealmar, Thanks for reporting this! We were stripping out too much from the URL (in order to get some normalization in place). Fixing this and pushing + updating current Youtube link who lost the `v`.
