### ISSUE TITLE
back links broken on blog

### ISSUE THREAD

**Issue by Papillard** [lewagon/www#570]
Some backlinks do not work on the blog see below

<img width="913" alt="screen shot 2018-01-30 at 18 19 29" src="https://user-images.githubusercontent.com/2471555/35580741-306f4212-05ea-11e8-8d05-6ff6503135d9.png">

**Comment by cedricmenteau** [comment]
I can't reproduce this bug 🤔 
![screen shot 2018-01-30 at 19 23 29](https://user-images.githubusercontent.com/6224412/35583740-2c6b63ea-05f3-11e8-9731-0971b662ddd8.png)
